CREATE SEQUENCE xxxt_ogrenci_id_S
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE
CACHE 10;

CREATE SEQUENCE xxxt_ders_id_S
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE
CACHE 10;

CREATE SEQUENCE xxxt_sinav_id_S
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE
CACHE 10;